
------------- ******* CREACION DE TABLAS DE BASE DE DATOS ******* ------------------------------
-- Crear tabla categoria de producto
CREATE TABLE categories(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	category VARCHAR(70) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	CONSTRAINT pk_id_categories PRIMARY KEY (id)
);

-- Crear tabla para los tipos de unidades de medida
CREATE TABLE measurements(
			id INT GENERATED BY DEFAULT AS IDENTITY,
			unit VARCHAR(100) NOT NULL,
			symbol VARCHAR(10) NULL,
			created_at TIMESTAMP NOT NULL,
			updated_at TIMESTAMP NULL,
			CONSTRAINT pk_measurement PRIMARY KEY (id)
);

-- Crear tabla productos
CREATE TABLE products(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	product_name VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	specification VARCHAR(100) NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	id_category INT NOT NULL,
	id_measurement INT NOT NULL,
	CONSTRAINT pk_id_product PRIMARY KEY (id),
	CONSTRAINT fk_id_category FOREIGN KEY (id_category) REFERENCES categories(id),
	CONSTRAINT fk_id_measurement FOREIGN KEY (id_measurement) REFERENCES measurements(id)
);

-- Crear tabla proovedores
CREATE TABLE suppliers(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	supplier_name VARCHAR(100) NOT NULL,
	number_phone VARCHAR(20) NULL,
	email VARCHAR(100) NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	CONSTRAINT pk_id_supplier PRIMARY KEY (id)
);

-- Crear tabla con de relacion M-M entre productos y proovedores
CREATE TABLE products_suppliers(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	price DECIMAL(10,3) NOT NULL,
	id_product INT NOT NULL,
	id_supplier INT NOT NULL,
	created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL,
	CONSTRAINT pk_product_supplier PRIMARY KEY (id),
	CONSTRAINT fk_id_product FOREIGN KEY (id_product) REFERENCES products(id),
	CONSTRAINT fk_id_supplier FOREIGN KEY (id_supplier) REFERENCES suppliers(id)
);
